#!/usr/bin/env bash

set -euo pipefail

(
    rustfmt "$WD/src/main.rs"
    cd "$WD/src" || return
    clippy-driver \
        -D warnings \
        -W clippy::pedantic \
        -A clippy::similar-names \
        -A clippy::too_many_lines \
        --test \
        "$WD/src/main.rs"
    rm "$WD/src/main"
)

export FLAGS=(
    -C "opt-level=0"
    -C "overflow-checks=yes"
    -C "panic=unwind"
    -W "absolute-paths-not-starting-with-crate"
    -W "anonymous-parameters"
    -W "deprecated-in-future"
    -W "explicit-outlives-requirements"
    -W "indirect-structural-match"
    -W "keyword-idents"
    -W "macro-use-extern-crate"
    -W "meta-variable-misuse"
    -W "missing-copy-implementations"
    -W "missing-debug-implementations"
    -W "non-ascii-idents"
    -W "trivial-casts"
    -W "trivial-numeric-casts"
    -W "unreachable-pub"
    -W "unused-extern-crates"
    -W "unused-import-braces"
    -W "unused-lifetimes"
    -W "unused-qualifications"
    -W "unused-results"
)
export RUST_BACKTRACE=1

set +u

if [ -z "$1" ]; then
    rustc -o "$WD/bin/test" "${FLAGS[@]}" --test "$WD/src/main.rs"
    "$WD/bin/test"
else
    rustc -o "$WD/bin/main" "${FLAGS[@]}" "$WD/src/main.rs"
    "$WD/bin/main" "$1"
fi
